version: '3.7'

services:

    lxldapg:
        image: lxldapg:1.0
        environment:
            - DISPLAY=${DISPLAY}
            - SSH_CONNECTION=${SSH_CONNECTION}
            - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
            - XMODIFIERS=${XMODIFIERS}
        ipc: host
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /tmp/.font-unix:/tmp/.font-unix
            - /tmp/.ICE-unix:/tmp/.ICE-unix
            - /tmp/.Test-unix:/tmp/.Test-unix
            - /tmp/.XIM-unix:/tmp/.XIM-unix
            - /home/admin/.Xauthority:/root/.Xauthority
            - /run/user/0:/run/user/0
            - /dev/shm:/dev/shm
            - ${PWD}/ldiffiles:/root/ldiffiles
            - ${PWD}/config/.lxldapg.toml:/root/.lxldapg.toml
            - ${PWD}/config/.ldaprc:/root/.ldaprc
        network_mode: "host"
        command: /bin/bash -c "/root/lxldapg" 
