version: '3.7'

services:

    lxldapg:
        image: lxldapg:1.0
        environment:
            - DISPLAY=${DISPLAY}
        ipc: host
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ${HOME}/.Xauthority:/root/.Xauthority
            - /dev/shm:/dev/shm
            - ${PWD}/ldiffiles:/root/ldiffiles
            - ${PWD}/config/.lxldapg.toml:/root/.lxldapg.toml
            - ${PWD}/config/.ldaprc:/root/.ldaprc
        network_mode: "host"
        command: /bin/bash -c "/root/lxldapg" 
